// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.CentralStation;

import ClassDiagram.Rover.RoverCommunicator;
import ClassDiagram.Types.Mission;
import ClassDiagram.Types.Position;
import java.awt.Image;

/************************************************************/
/**
 * 
 */
public interface DataManager {
	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Position getPositionOf(int roverID);

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Image getVideoOf(int roverID);

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public boolean getOperationalStatusOf(int roverID);

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Mission getMissionOf(int roverID);

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints();
	
	public RoverCommunicator[] getRoverCommunicators();
};
