// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.CentralStation;

import ClassDiagram.Types.Position;

/************************************************************/
/**
 * 
 */
public interface LocationManager {
	/**
	 * 
	 * @param position 
	 * @param roverID 
	 */
	public void validatePosition(Position position, int roverID);
};
