// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.CentralStation;

import ClassDiagram.Rover.RoverCommunicator;
import ClassDiagram.Types.Area;
import ClassDiagram.Types.Environment;

/************************************************************/
/**
 * 
 */
public class RewardPointsCalculator {
	/**
	 * 
	 */
	private int rewardPoints = 0;

	/**
	 * 
	 * @param environment 
	 * @param roverCommunicators 
	 */
	public void calculateRewardPoints(Environment environment, RoverCommunicator[] roverCommunicators) {
		for (RoverCommunicator rc : roverCommunicators) {
			for (Area a : environment.getAreas()) {
				if (a.getBoundary().contains(rc.getPosition())) {
					rewardPoints += a.getRewardPoint();
				}
			}
		}
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints() {
		return rewardPoints;
	}

	/**
	 * 
	 */
	public void RewardPointsCalculator() {
	}
};
