// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.CentralStation;

import ClassDiagram.CentralStation.DataManager;
import ClassDiagram.CentralStation.RewardPointsCalculator;
import ClassDiagram.CentralStation.RoverManager;
import ClassDiagram.Rover.RoverCommunicator;
import ClassDiagram.Types.Environment;
import ClassDiagram.Types.Mission;
import ClassDiagram.Types.Position;
import java.awt.Image;

/************************************************************/
/**
 * 
 */
public class RoverLord implements RoverManager, DataManager {
	/**
	 * 
	 */
	private RoverCommunicator[] roverCommunicator;
	/**
	 * 
	 */
	private RewardPointsCalculator rewardPointsCalculator;

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Position getPositionOf(int roverID) {
	}

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Image getVideoOf(int roverID) {
	}

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public boolean getOperationalStatusOf(int roverID) {
	}

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Mission getMissionOf(int roverID) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints() {
	}

	/**
	 * 
	 * @param roverID 
	 * @param mission 
	 */
	public void changeMissionOf(int roverID, Mission mission) {
	}

	/**
	 * 
	 * @param roverID 
	 */
	public void abortMissionOf(int roverID) {
	}

	/**
	 * 
	 * @param environment 
	 * @param rovers 
	 */
	public void RoverLord(Environment environment, RoverCommunicator[] rovers) {
	}

	/**
	 * 
	 */
	public void update() {
	}
};
