// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.CentralStation;

import ClassDiagram.Types.Mission;

/************************************************************/
/**
 * 
 */
public interface RoverManager {
	/**
	 * 
	 * @param roverID 
	 * @param mission 
	 */
	public void changeMissionOf(int roverID, Mission mission);

	/**
	 * 
	 * @param roverID 
	 */
	public void abortMissionOf(int roverID);
};
