// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Ui;

import ClassDiagram.CentralStation.DataManager;
import ClassDiagram.CentralStation.RoverManager;
import ClassDiagram.Types.Mission;

/************************************************************/
/**
 * 
 */
public class RoverView {
	/**
	 * 
	 */
	private DataManager dataManager;
	/**
	 * 
	 */
	private RoverManager roverManager;

	/**
	 * 
	 * @param mission 
	 */
	public void changeMission(Mission mission) {
	}

	/**
	 * 
	 * @param dataManager 
	 * @param roverManager 
	 */
	public void RoverView(DataManager dataManager, RoverManager roverManager) {
	}
};
