// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.PhysicalDevices;

import ClassDiagram.Types.Position;
import project.AbstractRobotSimulator;
import project.LocationController;
import simbad.sim.EnvironmentDescription;

/************************************************************/
/**
 * 
 */
public class MultipleLocationController extends LocationController {
	/**
	 * 
	 */
	private int numberOfSlots;
	/**
	 * 
	 */
	private int usedSlots;

	/**
	 * 
	 * @param position 
	 * @param radius 
	 * @param wd 
	 * @param numberOfSlots 
	 */
	public MultipleLocationController(Position position, double radius, EnvironmentDescription wd,
			int numberOfSlots) {
		super(new project.Point(position.x, position.z), radius, wd);
		this.numberOfSlots = numberOfSlots;
		usedSlots = 0;
	}
	
	@Override
	public boolean tryAcquire(AbstractRobotSimulator r) {
		// ugly: only use super.tryAcquire for range checking
		if (usedSlots < numberOfSlots && super.tryAcquire(r)) {
			super.release(r);
			usedSlots++;
			return true;
		}
		return false;
	}
	
	@Override
	public void release(AbstractRobotSimulator r) {
		if (usedSlots > 0) {
			usedSlots--;
		}
	}
};
