// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.Image;
import model.ClassDiagram.Mission;
import model.ClassDiagram.Position;

/************************************************************/
/**
 * 
 */
public interface DataManager {
	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Position getPositionOf(int roverID);

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Image getVideoOf(int roverID);

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public boolean getOperationalStatusOf(int roverID);

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Mission getMissionOf(int roverID);

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints();
};
