// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.Image;
import model.ClassDiagram.Observable;
import model.ClassDiagram.Position;
import model.ClassDiagram.SensorData;

/************************************************************/
/**
 * 
 */
public interface HardwareHandler extends Observable {
	/**
	 * 
	 * @param position 
	 */
	public void setDestination(Position position);

	/**
	 * 
	 */
	public void stop();

	/**
	 * 
	 * @return 
	 */
	public Image getImage();

	/**
	 * 
	 * @return 
	 */
	public Position getCurrentPosition();

	/**
	 * 
	 * @return 
	 */
	public SensorData getSensorData();
};
