// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.Position;

/************************************************************/
/**
 * 
 */
public interface LocationManager {
	/**
	 * 
	 * @param position 
	 * @param roverID 
	 */
	public void validatePosition(Position position, int roverID);
};
