// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.Observable;
import model.ClassDiagram.Point;

/************************************************************/
/**
 * 
 */
public interface MovementManager extends Observable {
	/**
	 * 
	 * @param point 
	 */
	public void goToPoint(Point point);
};
