// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.UpdateEvent;

/************************************************************/
/**
 * 
 */
public interface Observer {
	/**
	 * 
	 * @param updateEvent 
	 */
	public void update(UpdateEvent updateEvent);
};
