// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.HardwareHandler;
import model.ClassDiagram.Image;
import model.ClassDiagram.Observer;
import model.ClassDiagram.Position;
import model.ClassDiagram.SensorData;

/************************************************************/
/**
 * 
 */
public class Robot implements HardwareHandler {
	/**
	 * 
	 * @param observer 
	 */
	public void addObserver(Observer observer) {
	}

	/**
	 * 
	 * @param observer 
	 */
	public void removeObserver(Observer observer) {
	}

	/**
	 * 
	 */
	public void stop() {
	}

	/**
	 * 
	 * @param position 
	 */
	public void setDestination(Position position) {
	}

	/**
	 * 
	 * @return 
	 */
	public Image getImage() {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public Position getCurrentPosition() {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public SensorData getSensorData() {
		return null;
	}

	/**
	 * 
	 * @param position 
	 * @param name 
	 */
	public void Robot(Position position, String name) {
	}
};
