// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.DataManager;
import model.ClassDiagram.Mission;
import model.ClassDiagram.RoverManager;

/************************************************************/
/**
 * 
 */
public class RoverView {
	/**
	 * 
	 */
	private DataManager dataManager;
	/**
	 * 
	 */
	private RoverManager roverManager;

	/**
	 * 
	 * @param mission 
	 */
	public void changeMission(Mission mission) {
	}

	/**
	 * 
	 * @param dataManager 
	 * @param roverManager 
	 */
	public void RoverView(DataManager dataManager, RoverManager roverManager) {
	}
};
