// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.Fault;
import model.ClassDiagram.HardwareHandler;
import model.ClassDiagram.Image;
import model.ClassDiagram.LocationManager;
import model.ClassDiagram.Mission;
import model.ClassDiagram.MovementAI;
import model.ClassDiagram.MovementManager;
import model.ClassDiagram.Observer;
import model.ClassDiagram.Position;
import model.ClassDiagram.Robot;
import model.ClassDiagram.RoverCommunicator;
import model.ClassDiagram.SimpleStrategy;
import model.ClassDiagram.StrategyHandler;

/************************************************************/
/**
 * 
 */
public class Rover implements RoverCommunicator, Observer {
	/**
	 * 
	 */
	private StrategyHandler strategyHandler;
	/**
	 * 
	 */
	private MovementManager movementmanager;
	/**
	 * 
	 */
	private HardwareHandler hardwareHandler;

	/**
	 * 
	 * @param mission 
	 */
	public void changeMission(Mission mission) {
	}

	/**
	 * 
	 * @return 
	 */
	public Position getPosition() {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public Image getImage() {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean getOperationalStatus() {
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public Mission getMissionStatus() {
		return null;
	}

	/**
	 * 
	 */
	public void update() {
	}

	/**
	 * 
	 */
	public void abortMission() {
	}

	/**
	 * 
	 * @param fault 
	 */
	public void handleFault(Fault fault) {
	}

	/**
	 * 
	 * @param position 
	 * @param name 
	 * @param locationManager 
	 */
	public Rover(Position position, String name, LocationManager locationManager) {
	}

	@Override
	public void update(UpdateEvent updateEvent) {
		// TODO Auto-generated method stub
		
	}
};
