// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.DataManager;
import model.ClassDiagram.Environment;
import model.ClassDiagram.Image;
import model.ClassDiagram.LocationManager;
import model.ClassDiagram.Mission;
import model.ClassDiagram.Position;
import model.ClassDiagram.RoverCommunicator;
import model.ClassDiagram.RoverManager;

/************************************************************/
/**
 * 
 */
public class RoverLord implements RoverManager, DataManager, LocationManager {
	/**
	 * 
	 */
	private RoverCommunicator[] roverCommunicator;

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Position getPositionOf(int roverID) {
		return null;
	}

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Image getVideoOf(int roverID) {
		return null;
	}

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public boolean getOperationalStatusOf(int roverID) {
		return false;	
	}

	/**
	 * 
	 * @param roverID 
	 * @return 
	 */
	public Mission getMissionOf(int roverID) {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints() {
		return 0;
	}

	/**
	 * 
	 * @param roverID 
	 * @param mission 
	 */
	public void changeMissionOf(int roverID, Mission mission) {
	}

	/**
	 * 
	 * @param roverID 
	 */
	public void abortMissionOf(int roverID) {
	}

	/**
	 * 
	 * @param environment 
	 * @param rovers 
	 */
	public void RoverLord(Environment environment, RoverCommunicator[] rovers) {
	}

	@Override
	public void validatePosition(Position position, int roverID) {
		// TODO Auto-generated method stub
		
	}
};
