// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.Mission;

/************************************************************/
/**
 * 
 */
public interface RoverManager {
	/**
	 * 
	 * @param roverID 
	 * @param mission 
	 */
	public void changeMissionOf(int roverID, Mission mission);

	/**
	 * 
	 * @param roverID 
	 */
	public void abortMissionOf(int roverID);
};
