// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.Mission;
import model.ClassDiagram.StrategyHandler;

/************************************************************/
/**
 * 
 */
public class SimpleStrategy implements StrategyHandler {
	/**
	 * 
	 * @param mission 
	 */
	public void chooseStrategy(Mission mission) {
	}

	/**
	 * 
	 */
	public void SimpleStrategy() {
	}
};
