// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model.ClassDiagram;

import model.ClassDiagram.Mission;

/************************************************************/
/**
 * 
 */
public interface StrategyHandler {
	/**
	 * 
	 * @param mission 
	 */
	public void chooseStrategy(Mission mission);
};
