// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;


import ClassDiagram.Types.Boundary;
import project.LocationController;

/************************************************************/
/**
 * 
 */
public class Area {
	/**
	 * 
	 */
	private Boundary boundary;
	/**
	 * 
	 */
	public LocationController locationController;
	/**
	 * 
	 */
	private String roomType;

	private boolean isPhysical;
	
	private int rewardPoint;
	
	private boolean requiresWaiting;
	
	
	/**
	 * 
	 * @param boundary 
	 * @param restricted 
	 * @param locationController 
	 * @param type 
	 * @param isPhysical 
	 */
	public Area(Boundary boundary, LocationController locationController, String type,
			boolean isPhysical, int rewardPoint, boolean requiresWaiting) {
		this.boundary = boundary;
		this.locationController = locationController;
		this.roomType = type;
		this.isPhysical = isPhysical;
		this.rewardPoint = rewardPoint;
		this.requiresWaiting = requiresWaiting;
	}

	/**
	 * 
	 * @return 
	 */
	public Boundary getBoundary() {
		return boundary;
	}

	/**
	 * 
	 * @return 
	 */
	public LocationController getLocationController() {
		return locationController;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isPhysical() {
		return isPhysical;
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoint() {
		return rewardPoint;
	}
	
	public String getRoomType() {
		return roomType;
	}
	
	public boolean requiresWaiting() {
		return requiresWaiting;
	}
};
