// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.Boundary;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Area {
	/**
	 * 
	 */
	public Boundary boundary;
	/**
	 * 
	 */
	public boolean isRestricted;
	/**
	 * 
	 */
	public List<Integer> roversInside;
};
