// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.Position;

/************************************************************/
/**
 * 
 */
public class Boundary {
	/**
	 * 
	 */
	private double width;
	/**
	 * 
	 */
	private double height;
	/**
	 * 
	 */
	private Position position;

	/**
	 * 
	 * @param position 
	 * @return 
	 */
	public boolean contains(Position position) {
	}

	/**
	 * 
	 * @param width 
	 * @param height 
	 * @param position 
	 */
	public void Boundary(double width, double height, Position position) {
	}

	/**
	 * 
	 * @return 
	 */
	public double getWidth() {
	}

	/**
	 * 
	 * @return 
	 */
	public double getHeight() {
	}

	/**
	 * 
	 * @return 
	 */
	public Position getPosition() {
	}
};
