// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.Position;

/************************************************************/
/**
 * 
 */
public class Boundary {
	/**
	 * 
	 */
	private double width;
	/**
	 * 
	 */
	private double height;
	/**
	 * 
	 */
	private Position position;

	/**
	 * 
	 * @param position 
	 * @return 
	 */
	public boolean contains(Position position) {
		return position.x > this.position.x && position.x < this.position.x + width &&
				position.z > this.position.z && position.z < this.position.z + height;
	}

	/**
	 * 
	 * @param width 
	 * @param height 
	 * @param position 
	 */
	public Boundary(double width, double height, Position position) {
		this.width = width;
		this.height = height;
		this.position = position;
	}

	/**
	 * 
	 * @return 
	 */
	public double getWidth() {
		return width;
	}

	/**
	 * 
	 * @return 
	 */
	public double getHeight() {
		return height;
	}

	/**
	 * 
	 * @return 
	 */
	public Position getPosition() {
		return position;
	}
};
