// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.Area;

/************************************************************/
/**
 * 
 */
public class Environment {
	/**
	 * 
	 */
	public Area[] areas;

	/**
	 * 
	 * @param areas 
	 */
	public void Environment(Area[] areas) {
	}

	/**
	 * 
	 * @return 
	 */
	public Area[] getAreas() {
	}
};
