// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.FaultType;

/************************************************************/
/**
 * 
 */
public class Fault {
	/**
	 * 
	 */
	public FaultType faultType;

	/**
	 * 
	 * @param faultType 
	 */
	public void Fault(FaultType faultType) {
	}
};
