// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.Point;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Mission {
	/**
	 * 
	 */
	private List<Point> finishedPoints;
	/**
	 * 
	 */
	private List<Point> remainingPoints;

	/**
	 * 
	 * @return 
	 */
	public boolean isFinished() {
		return false;
	}

	/**
	 * 
	 * @param point 
	 */
	public void setPointFinished(Point point) {
	}

	/**
	 * 
	 * @param points 
	 */
	public Mission(List<Point> points) {
	}

	/**
	 * 
	 * @return 
	 */
	public List<Point> getFinishedPoints() {
		return finishedPoints;
	}

	/**
	 * 
	 * @return 
	 */
	public List<Point> getRemainingPoints() {
		return remainingPoints;
	}
};
