// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Mission {
	/**
	 * 
	 */
	public List<Point> finishedPoints;
	/**
	 * 
	 */
	public List<Point> remainingPoints;
};
