// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.Position;

/************************************************************/
/**
 * 
 */
public class Point {
	/**
	 * 
	 */
	public Position position;
	/**
	 * 
	 */
	public boolean status;
};
