// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import project.Point;

/************************************************************/
/**
 * 
 */
public class Position {
	/**
	 * 
	 */
	public double x;
	/**
	 * 
	 */
	public double z;

	/**
	 * 
	 * @param x 
	 * @param z 
	 */
	public Position(double x, double z) {
		this.x = x;
		this.z = z;
	}

	public Position(Point position) {
		this(position.getX(), position.getZ());
	}
};
