// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

/************************************************************/
/**
 * 
 */
public class Position {
	/**
	 * 
	 */
	public double x;
	/**
	 * 
	 */
	public double z;
};
