// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.Boundary;
import ClassDiagram.Types.Position;

/************************************************************/
/**
 * 
 */
public class RectangularBoundary extends Boundary {
	/**
	 * 
	 */
	private double width;
	/**
	 * 
	 */
	private double height;

	/**
	 * 
	 * @param position 
	 * @return 
	 */
	public boolean contains(Position position) {
		return position.x >= this.position.x && 
				position.x <= this.position.x + width &&
				position.z >= this.position.z && 
				position.z <= this.position.z + height ;
	}

	/**
	 * 
	 * @param width 
	 * @param height 
	 * @param position 
	 */
	public RectangularBoundary(double width, double height, Position position) {
		super(position);
		this.width = width;
		this.height = height;
	}

	/**
	 * 
	 * @return 
	 */
	public double getWidth() {
		return width;
	}

	/**
	 * 
	 * @return 
	 */
	public double getHeight() {
		return height;
	}
};
