// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

/************************************************************/
/**
 * 
 */
public enum RoomType {
	/**
	 * 
	 */
	Office,
	/**
	 * 
	 */
	TeacherRoom,
	/**
	 * 
	 */
	WifiZone,
	/**
	 * 
	 */
	EatingSpace;
};
