// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

/************************************************************/
/**
 * 
 */
public class SensorData {
	/**
	 * 
	 */
	public double frontDistance;
	/**
	 * 
	 */
	public double rightDistance;
	/**
	 * 
	 */
	public double backDistance;
	/**
	 * 
	 */
	public double leftDistance;

	/**
	 * 
	 * @param frontDistance 
	 * @param rightDistance 
	 * @param backDistance 
	 * @param leftDistance 
	 */
	public void SensorData(double frontDistance, double rightDistance, double backDistance, double leftDistance) {
	}
};
