// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

/************************************************************/
/**
 * 
 */
public class SensorData {
	/**
	 * 
	 */
	public double frontDistance;
	/**
	 * 
	 */
	public double rightDistance;
	/**
	 * 
	 */
	public double backDistance;
	/**
	 * 
	 */
	public double leftDistance;
};
