// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

/************************************************************/
/**
 * 
 */
public class SensorData {
	/**
	 * 
	 */
	public double frontDistance;
	/**
	 * 
	 */
	public double rightDistance;
	/**
	 * 
	 */
	public double backDistance;
	/**
	 * 
	 */
	public double leftDistance;

	/**
	 * 
	 * @param frontDistance 
	 * @param rightDistance 
	 * @param backDistance 
	 * @param leftDistance 
	 */
	public SensorData(double frontDistance, double rightDistance, double backDistance, double leftDistance) {
		this.frontDistance = frontDistance;
		this.rightDistance = rightDistance;
		this.backDistance = backDistance;
		this.leftDistance = leftDistance;
	}
	
	@Override
	public boolean equals(Object o) {
		if (o != null && o.getClass() == this.getClass()) {
			SensorData sd = (SensorData)o;
			if (sd.frontDistance == frontDistance && sd.rightDistance == rightDistance &&
					sd.backDistance == backDistance && sd.leftDistance == leftDistance) {
				return true;
			}
		}
		return false;
	}
	
	@Override
	public String toString() {
		return String.format("NWSE=[%f,%f,%f,%f]", frontDistance, leftDistance, backDistance, rightDistance);
	}
};
