// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

/************************************************************/
/**
 * 
 */
public enum UpdateEventType {
	/**
	 * The data will be a Position object
	 */
	PositionUpdate,
	/**
	 * The data will be a SensorData object
	 */
	SensorUpdate,
	/**
	 * 
	 */
	PointReachedUpdate;
};
