// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.UpdateEventType;
import java.lang.Object;

/************************************************************/
/**
 * 
 */
public class UpdateEvent {
	/**
	 * 
	 */
	public UpdateEventType type;
	/**
	 * 
	 */
	public Object data;

	/**
	 * 
	 * @param type 
	 * @param data 
	 */
	public UpdateEvent(UpdateEventType type, Object data) {
	}
};
