// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Types;

import ClassDiagram.Types.UpdateEventType;
import java.lang.Object;

/************************************************************/
/**
 * 
 */
public class UpdateEvent {
	/**
	 * 
	 */
	public UpdateEventType updateEventType;
	/**
	 * 
	 */
	public Object data;
};
