// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Rover;

import ClassDiagram.Rover.Observable;
import ClassDiagram.Types.Position;
import ClassDiagram.Types.SensorData;
import java.awt.Image;

/************************************************************/
/**
 * 
 */
public interface HardwareHandler extends Observable {
	/**
	 * 
	 * @param position 
	 */
	public void setDestination(Position position);

	/**
	 * 
	 */
	public void stop();

	/**
	 * 
	 * @return 
	 */
	public Image getImage();

	/**
	 * 
	 * @return 
	 */
	public Position getCurrentPosition();

	/**
	 * 
	 * @return 
	 */
	public SensorData getSensorData();
};
