// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Rover;

import ClassDiagram.Rover.Observable;
import ClassDiagram.Types.Point;

/************************************************************/
/**
 * 
 */
public interface MovementManager extends Observable {
	/**
	 * 
	 * @param point 
	 */
	public void goToPoint(Point point);
};
