// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Rover;

import ClassDiagram.Rover.Observer;

/************************************************************/
/**
 * 
 */
public interface Observable {
	/**
	 * 
	 * @param observer 
	 */
	public void addObserver(Observer observer);

	/**
	 * 
	 * @param observer 
	 */
	public void removeObserver(Observer observer);
};
