// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Rover;

import ClassDiagram.Types.UpdateEvent;

/************************************************************/
/**
 * 
 */
public interface Observer {
	/**
	 * 
	 * @param updateEvent 
	 */
	public void update(UpdateEvent updateEvent);
};
