// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Rover;

import ClassDiagram.Rover.StrategyHandler;
import ClassDiagram.Types.Mission;

/************************************************************/
/**
 * 
 */
public class SimpleStrategy implements StrategyHandler {
	/**
	 * 
	 * @param mission 
	 */
	public void chooseStrategy(Mission mission) {
	}

	/**
	 * 
	 */
	public void SimpleStrategy() {
	}
};
