// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Rover;

import ClassDiagram.Types.Mission;
import ClassDiagram.Types.Position;
import ClassDiagram.Types.Environment;

/************************************************************/
/**
 * 
 */
public interface StrategyHandler {

	/**
	 * 
	 * @param mission 
	 * @param position 
	 * @param environment 
	 */
	public void chooseStrategy(Mission mission, Position position, Environment environment);
};
