// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Rover;

import ClassDiagram.Types.Mission;

/************************************************************/
/**
 * 
 */
public interface StrategyHandler {
	/**
	 * 
	 * @param mission 
	 */
	public void chooseStrategy(Mission mission);
};
